export enum ReportReason {
  PROPAGANDA_OF_VIOLENCE = 'PROPAGANDA_OF_VIOLENCE',
  TERRORISM = 'TERRORISM',
  VIOLATE_THE_RULES = 'VIOLATE_THE_RULES',
  SENSITIVE_CONTENT_OF_CHILDREN = 'SENSITIVE_CONTENT_OF_CHILDREN'
}
